### ISSUE TITLE
Py interface Segmenter vs Chedaka not working

### ISSUE THREAD

**Issue by swadharma-me** [ambuda-org/vidyut-py#1]
I want to use the python interface of the Vidhyut-py

https://github.com/ambuda-org/vidyut-py/blob/85c8359881cf8e67ab51c50b6d51ce95c865f254/test.py#L1

it says Segmenter module not found 

I have replaced "Segmenter" with Chedaka as I figured that could be the case and when I do that I encounter the error "pyo3_runtime.PanicException: called `Option::unwrap()` on a `None` value" 

Can you please help ?

**Comment by akprasad** [comment]
Thank you very much for filing this issue!

Our Python bindings are currently unstable, and we're working on stabilizing this API and adding better documentation. I'll follow up here in a few days with a working setup.

I'm curious -- can you say more about how you plan to use Vidyut?

**Comment by swadharma-me** [comment]
Thanks a ton for quick response. I do not have a specific idea in mind on how to use it. I have been wanting to have Sandhi Split done so that I can read texts more easily.

**Comment by akprasad** [comment]
I have updated the bindings as well as their associated documentation. For usage examples, please see the tests in `test`.

Also, please install these bindings directly from GitHub:

```
pip install git+https://github.com/ambuda-org/vidyut-py.git
```

Would you like to help me improve this library? All you have to do is use the library and let me know where the API is awkward or the documentation is weak.
